# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flow_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 437)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/flow-icon-png-8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Flow_Concentration_Profile = QtWidgets.QGroupBox(self.centralwidget)
        self.Flow_Concentration_Profile.setGeometry(QtCore.QRect(20, 20, 261, 251))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Flow_Concentration_Profile.setFont(font)
        self.Flow_Concentration_Profile.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Flow_Concentration_Profile.setObjectName("Flow_Concentration_Profile")
        self.Uploaded_Image = QtWidgets.QLabel(self.Flow_Concentration_Profile)
        self.Uploaded_Image.setGeometry(QtCore.QRect(30, 30, 200, 200))
        self.Uploaded_Image.setObjectName("Uploaded_Image")
        self.Uploaded_Image.setStyleSheet("background-color:#fff;");
        self.Scale = QtWidgets.QGroupBox(self.centralwidget)
        self.Scale.setGeometry(QtCore.QRect(290, 20, 91, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Scale.setFont(font)
        self.Scale.setObjectName("Scale")
        self.High = QtWidgets.QLabel(self.Scale)
        self.High.setGeometry(QtCore.QRect(40, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.High.setFont(font)
        self.High.setObjectName("High")
        self.Medium = QtWidgets.QLabel(self.Scale)
        self.Medium.setGeometry(QtCore.QRect(40, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Medium.setFont(font)
        self.Medium.setObjectName("Medium")
        self.Low = QtWidgets.QLabel(self.Scale)
        self.Low.setGeometry(QtCore.QRect(40, 210, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Low.setFont(font)
        self.Low.setObjectName("Low")
        self.Scale_image = QtWidgets.QLabel(self.Scale)
        self.Scale_image.setGeometry(QtCore.QRect(10, 30, 21, 201))
        self.Scale_image.setText("")
        self.Scale_image.setPixmap(QtGui.QPixmap("./images/ind2.png"))
        self.Scale_image.setScaledContents(True)
        self.Scale_image.setObjectName("Scale_image")
        self.Upload_Label = QtWidgets.QLabel(self.centralwidget)
        self.Upload_Label.setGeometry(QtCore.QRect(40, 320, 141, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Upload_Label.setFont(font)
        self.Upload_Label.setObjectName("Upload_Label")
        self.Browse_Image = QtWidgets.QToolButton(self.centralwidget)
        self.Browse_Image.setGeometry(QtCore.QRect(330, 320, 31, 28))
        self.Browse_Image.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/browse-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Browse_Image.setIcon(icon1)
        self.Browse_Image.setIconSize(QtCore.QSize(22, 22))
        self.Browse_Image.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.Browse_Image.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Browse_Image.setAutoRaise(False)
        self.Browse_Image.setArrowType(QtCore.Qt.NoArrow)
        self.Browse_Image.setObjectName("Browse_Image")
        self.Show_Image_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Show_Image_Name.setGeometry(QtCore.QRect(180, 320, 141, 20))
        self.Show_Image_Name.setObjectName("Show_Image_Name")
        self.Actual_Flow = QtWidgets.QGroupBox(self.centralwidget)
        self.Actual_Flow.setGeometry(QtCore.QRect(400, 20, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Actual_Flow.setFont(font)
        self.Actual_Flow.setObjectName("Actual_Flow")
        self.Actual_Flow_Selection = QtWidgets.QComboBox(self.Actual_Flow)
        self.Actual_Flow_Selection.setGeometry(QtCore.QRect(120, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Actual_Flow_Selection.setFont(font)
        self.Actual_Flow_Selection.setObjectName("Actual_Flow_Selection")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Actual_Flow_Selection.addItem("")
        self.Select_Label = QtWidgets.QLabel(self.Actual_Flow)
        self.Select_Label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Select_Label.setFont(font)
        self.Select_Label.setObjectName("Select_Label")
        self.Prediction = QtWidgets.QGroupBox(self.centralwidget)
        self.Prediction.setGeometry(QtCore.QRect(400, 100, 261, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Prediction.setFont(font)
        self.Prediction.setObjectName("Prediction")
        self.Result_text = QtWidgets.QPlainTextEdit(self.Prediction)
        self.Result_text.setGeometry(QtCore.QRect(20, 30, 221, 141))
        self.Result_text.setObjectName("Result_text")
        self.Identify_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Identify_Button.setGeometry(QtCore.QRect(460, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Identify_Button.setFont(font)
        self.Identify_Button.setObjectName("Identify_Button")
        self.Save_Results = QtWidgets.QPushButton(self.centralwidget)
        self.Save_Results.setGeometry(QtCore.QRect(460, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Save_Results.setFont(font)
        self.Save_Results.setObjectName("Save_Results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.New_File = QtWidgets.QAction(MainWindow)
        self.New_File.setShortcutVisibleInContextMenu(True)
        self.New_File.setObjectName("New_File")
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.menuFile.addAction(self.New_File)
        self.menuFile.addAction(self.Save)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Multiphase Flow Identifier"))
        self.Flow_Concentration_Profile.setTitle(_translate("MainWindow", "Flow Concentration Profile"))
        self.Scale.setTitle(_translate("MainWindow", " Scale"))
        self.High.setText(_translate("MainWindow", "High"))
        self.Medium.setText(_translate("MainWindow", "Medium"))
        self.Low.setText(_translate("MainWindow", "Low"))
        self.Upload_Label.setText(_translate("MainWindow", "Upload Flow Data"))
        self.Browse_Image.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.Actual_Flow.setTitle(_translate("MainWindow", "Actual Flow"))
        self.Actual_Flow_Selection.setItemText(0, _translate("MainWindow", "...."))
        self.Actual_Flow_Selection.setItemText(1, _translate("MainWindow", "Annular 25 mm"))
        self.Actual_Flow_Selection.setItemText(2, _translate("MainWindow", "Annular 75 mm"))
        self.Actual_Flow_Selection.setItemText(3, _translate("MainWindow", "Full Flow"))
        self.Actual_Flow_Selection.setItemText(4, _translate("MainWindow", "3 Quarter Flow"))
        self.Actual_Flow_Selection.setItemText(5, _translate("MainWindow", "Half Flow"))
        self.Actual_Flow_Selection.setItemText(6, _translate("MainWindow", "Quarter Flow"))
        self.Select_Label.setText(_translate("MainWindow", "Select Flow Type"))
        self.Prediction.setTitle(_translate("MainWindow", "Predicted Flow"))
        self.Identify_Button.setText(_translate("MainWindow", "Identify"))
        self.Save_Results.setText(_translate("MainWindow", "Save Result"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.New_File.setText(_translate("MainWindow", "New File"))
        self.New_File.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.Save.setText(_translate("MainWindow", "Save "))
        self.Save.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
